# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  node: circle/node@5.2.0
  
jobs: 
  test:
    executor: node/default
    steps:
      - checkout
      - run: sudo npm install -g npm@latest
      - node/install-packages:
        cache-path: ~/project/node_modules
        override-ci-command: npm install
      - run: npm run test
# Orchestrate jobs using workflows
# See: https://circleci.com/docs/workflows/ & https://circleci.com/docs/configuration-reference/#workflows
workflows:
  say-hello-workflow: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - test
